const tasks = [
  {
    id: 1,
    createdBy: 'Johnny',
    description: 'refactor components',
    status: 'todo',
    completionDate: new Date(),
  },
  {
    id: 2,
    createdBy: 'Mary',
    description: 'marketing work',
    status: 'todo',
    completionDate: new Date(),
  },
  {
    id: 3,
    createdBy: 'Samuel',
    description: 'design logo',
    status: 'todo',
    completionDate: new Date(),
  },
  {
    id: 4,
    createdBy: 'Lisa',
    description: 'design header',
    status: 'todo',
    completionDate: new Date(),
  },
  {
    id: 5,
    createdBy: 'Jim',
    description: 'update vscode',
    status: 'done',
    completionDate: new Date(),
  },
  {
    id: 6,
    createdBy: 'Alice',
    description: 'update oauth',
    status: 'done',
    completionDate: new Date(),
  },
  {
    id: 7,
    createdBy: 'Daniel',
    description: 'changeover localSecrets.js',
    status: 'done',
    completionDate: new Date(),
  },
  {
    id: 8,
    createdBy: 'Gene',
    description: 'oversee merge',
    status: 'done',
    completionDate: new Date(),
  },
  {
    id: 9,
    createdBy: 'David',
    description: 'build component tree',
    status: 'in-progress',
    completionDate: new Date(),
  },
  {
    id: 10,
    createdBy: 'Michael',
    description: 'diagram changes',
    status: 'in-progress',
    completionDate: new Date(),
  },
  {
    id: 11,
    createdBy: 'Donald',
    description: 'update layout',
    status: 'in-progress',
    completionDate: new Date(),
  },
  {
    id: 12,
    createdBy: 'Tim',
    description: 'modularize css',
    status: 'in-progress',
    completionDate: new Date(),
  },
  {
    id: 13,
    createdBy: 'Sarah',
    description: 'write user stories',
    status: 'review',
    completionDate: new Date(),
  },
  {
    id: 14,
    createdBy: 'Kim',
    description: 'refactor db',
    status: 'review',
    completionDate: new Date(),
  },
  {
    id: 15,
    createdBy: 'Trainer',
    description: 'update models',
    status: 'review',
    completionDate: new Date(),
  },
  {
    id: 16,
    createdBy: 'Mohammad',
    description: 'write gatekeeping middleware',
    status: 'review',
    completionDate: new Date(),
  },
  {
    id: 17,
    createdBy: 'Blake',
    description: 'reverse linked list',
    status: 'done',
    completionDate: new Date(),
  },
  {
    id: 18,
    createdBy: 'Natasha',
    description: 'buy popcorn',
    status: 'in-progress',
    completionDate: new Date(),
  },
  {
    id: 19,
    createdBy: 'George',
    description: 'play guitar hero',
    status: 'todo',
    completionDate: new Date(),
  },
  {
    id: 20,
    createdBy: 'Marguerite',
    description: 'deploy on heroku',
    status: 'review',
    completionDate: new Date(),
  },
]
