const timeStamp = new Date()

module.exports = [
  {
    userId: 1,
    taskId: 1,
    text: 'On track and on time, what a perfect combo :D',
    editTimeStamp: timeStamp,
  },
  {
    userId: 2,
    taskId: 1,
    text: 'What a great user experience, bravo!',
    editTimeStamp: timeStamp,
  },
  {
    userId: 3,
    taskId: 2,
    text: 'My project manager rates this work very fabulous dude',
    editTimeStamp: timeStamp,
  },
  {
    userId: 4,
    taskId: 2,
    text: 'It is amazing not just excellent!',
    editTimeStamp: timeStamp,
  },
  {
    userId: 1,
    taskId: 3,
    text: 'This animation blew my mind.',
    editTimeStamp: timeStamp,
  },
  {
    userId: 2,
    taskId: 3,
    text: 'Yes yes yes yes yes yes.',
    editTimeStamp: timeStamp,
  },
  {userId: 3, taskId: 4, text: 'Great typeface!', editTimeStamp: timeStamp},
  {
    userId: 4,
    taskId: 4,
    text: 'Exquisite. So clean.',
    editTimeStamp: timeStamp,
  },
  {
    userId: 1,
    taskId: 5,
    text: 'Mission accomplished. It is sleek!!',
    editTimeStamp: timeStamp,
  },
  {
    userId: 2,
    taskId: 5,
    text: 'Absolutely nailed it, well done!',
    editTimeStamp: timeStamp,
  },
  {
    userId: 3,
    taskId: 6,
    text: 'These are incredible and classic!',
    editTimeStamp: timeStamp,
  },
  {
    userId: 4,
    taskId: 6,
    text: 'I think I am crying. It is that killer.',
    editTimeStamp: timeStamp,
  },
  {userId: 1, taskId: 7, text: 'Such fabulous.', editTimeStamp: timeStamp},
  {
    userId: 2,
    taskId: 7,
    text: 'Background image, style, type, shot – sleek dude',
    editTimeStamp: timeStamp,
  },
  {userId: 3, taskId: 8, text: 'Wow love it!', editTimeStamp: timeStamp},
  {
    userId: 4,
    taskId: 8,
    text: 'Beastly work you have here.',
    editTimeStamp: timeStamp,
  },
  {
    userId: 1,
    taskId: 9,
    text: 'Nice use of blue in this mockup!',
    editTimeStamp: timeStamp,
  },
  {
    userId: 2,
    taskId: 9,
    text: 'Gorgeous :) I love the use of blur and lines!',
    editTimeStamp: timeStamp,
  },
  {
    userId: 3,
    taskId: 10,
    text: 'I want to learn this kind of layout! Teach me.',
    editTimeStamp: timeStamp,
  },
  {
    userId: 4,
    taskId: 10,
    text: 'Overly splendid notification =)',
    editTimeStamp: timeStamp,
  },
  {
    userId: 1,
    taskId: 11,
    text: 'Such job, many shade, so radiant',
    editTimeStamp: timeStamp,
  },
  {
    userId: 2,
    taskId: 11,
    text: 'This dropdown menu has navigated right into my heart.',
    editTimeStamp: timeStamp,
  },
  {
    userId: 3,
    taskId: 12,
    text: 'This is radiant work!',
    editTimeStamp: timeStamp,
  },
  {userId: 4, taskId: 12, text: 'Just amazing =)', editTimeStamp: timeStamp},
  {
    userId: 1,
    taskId: 13,
    text: 'This component blew my mind.',
    editTimeStamp: timeStamp,
  },
  {
    userId: 2,
    taskId: 13,
    text: 'Mission accomplished. It is appealing m8',
    editTimeStamp: timeStamp,
  },
  {userId: 3, taskId: 14, text: 'Contrast.', editTimeStamp: timeStamp},
  {
    userId: 4,
    taskId: 14,
    text:
      'Immensely thought out! Engaging. It keeps your mind occupied while you wait.',
    editTimeStamp: timeStamp,
  },
  {
    userId: 1,
    taskId: 15,
    text: 'Tremendously killer webapp!!',
    editTimeStamp: timeStamp,
  },
  {userId: 2, taskId: 15, text: 'Trying it now.', editTimeStamp: timeStamp},
  {
    userId: 3,
    taskId: 16,
    text: 'Why go to college? There is Google.',
    editTimeStamp: timeStamp,
  },
  {
    userId: 4,
    taskId: 16,
    text: 'I think I am crying. It is LITERALLY that classic.',
    editTimeStamp: timeStamp,
  },
  {
    userId: 1,
    taskId: 17,
    text: 'Nice use of contrast in this experience m8',
    editTimeStamp: timeStamp,
  },
  {
    userId: 2,
    taskId: 17,
    text: 'Incredible work you have here.',
    editTimeStamp: timeStamp,
  },
  {
    userId: 3,
    taskId: 18,
    text: 'So simple and fab!!',
    editTimeStamp: timeStamp,
  },
  {
    userId: 4,
    taskId: 18,
    text: 'Such CSS, many typography, so neat',
    editTimeStamp: timeStamp,
  },
  {userId: 1, taskId: 19, text: 'Yup.', editTimeStamp: timeStamp},
  {
    userId: 2,
    taskId: 19,
    text: 'Incredibly well thought out! Cannot wait to try it out.',
    editTimeStamp: timeStamp,
  },
  {userId: 3, taskId: 20, text: 'Such sublime.', editTimeStamp: timeStamp},
  {
    userId: 4,
    taskId: 20,
    text: 'My work colleagues rate this job very sleek!',
    editTimeStamp: timeStamp,
  },
  {
    userId: 1,
    taskId: 21,
    text: 'Heyo!',
    editTimeStamp: timeStamp,
  },
  {
    userId: 2,
    taskId: 21,
    text: 'Nice work!',
    editTimeStamp: timeStamp,
  },
  {
    userId: 3,
    taskId: 22,
    text: 'Redux is hard.',
    editTimeStamp: timeStamp,
  },
  {
    userId: 4,
    taskId: 22,
    text: '... useContext is also hard :(',
    editTimeStamp: timeStamp,
  },
  {
    userId: 1,
    taskId: 23,
    text: 'you got this!',
    editTimeStamp: timeStamp,
  },
  {
    userId: 2,
    taskId: 23,
    text: 'go for it!',
    editTimeStamp: timeStamp,
  },
  {
    userId: 3,
    taskId: 24,
    text: 'i am only a dog but i think this is really well done',
    editTimeStamp: timeStamp,
  },
  {
    userId: 4,
    taskId: 24,
    text: 'keep at it!',
    editTimeStamp: timeStamp,
  },
  {
    userId: 1,
    taskId: 25,
    text: 'anyone mind resending this file?',
    editTimeStamp: timeStamp,
  },
  {
    userId: 2,
    taskId: 25,
    text: 'this made my computer explode hahaha',
    editTimeStamp: timeStamp,
  },
  {
    userId: 3,
    taskId: 26,
    text: 'anyone need a hand on this?',
    editTimeStamp: timeStamp,
  },
  {
    userId: 4,
    taskId: 26,
    text: 'let office space this',
    editTimeStamp: timeStamp,
  },
  {
    userId: 1,
    taskId: 27,
    text: 'postgres is acting up again ...',
    editTimeStamp: timeStamp,
  },
  {
    userId: 2,
    taskId: 27,
    text: 'markdown rules!',
    editTimeStamp: timeStamp,
  },
  {
    userId: 3,
    taskId: 28,
    text: 'anyone know what an invariant violation is?',
    editTimeStamp: timeStamp,
  },
  {
    userId: 4,
    taskId: 28,
    text: 'quick reboot should solve that',
    editTimeStamp: timeStamp,
  },
  {
    userId: 1,
    taskId: 29,
    text: 'what is OOP?',
    editTimeStamp: timeStamp,
  },
  {
    userId: 2,
    taskId: 29,
    text: 'best UI yet! way to go :D',
    editTimeStamp: timeStamp,
  },
  {
    userId: 3,
    taskId: 30,
    text: 'i like turtles',
    editTimeStamp: timeStamp,
  },
  {
    userId: 4,
    taskId: 30,
    text: 'i too like turtles',
    editTimeStamp: timeStamp,
  },
  {
    userId: 1,
    taskId: 31,
    text: 'Mmmmhmmm.',
    editTimeStamp: timeStamp,
  },
  {
    userId: 2,
    taskId: 31,
    text: 'nice responsive header!',
    editTimeStamp: timeStamp,
  },
  {
    userId: 3,
    taskId: 32,
    text: 'i really need to learn bootstrap',
    editTimeStamp: timeStamp,
  },
  {
    userId: 4,
    taskId: 32,
    text: 'keep pushing everyone! we are KILLING it hahaha',
    editTimeStamp: timeStamp,
  },
]
