module.exports = [
  {projectId: 1, columnId: 1, createdAt: new Date(), updatedAt: new Date()},
  {projectId: 1, columnId: 2, createdAt: new Date(), updatedAt: new Date()},
  {projectId: 1, columnId: 3, createdAt: new Date(), updatedAt: new Date()},
  {projectId: 1, columnId: 4, createdAt: new Date(), updatedAt: new Date()},
  {projectId: 2, columnId: 5, createdAt: new Date(), updatedAt: new Date()},
  {projectId: 2, columnId: 6, createdAt: new Date(), updatedAt: new Date()},
  {projectId: 2, columnId: 7, createdAt: new Date(), updatedAt: new Date()},
  {projectId: 2, columnId: 8, createdAt: new Date(), updatedAt: new Date()},
  {projectId: 3, columnId: 9, createdAt: new Date(), updatedAt: new Date()},
  {projectId: 3, columnId: 10, createdAt: new Date(), updatedAt: new Date()},
  {projectId: 3, columnId: 11, createdAt: new Date(), updatedAt: new Date()},
  {projectId: 3, columnId: 12, createdAt: new Date(), updatedAt: new Date()},
  {projectId: 4, columnId: 13, createdAt: new Date(), updatedAt: new Date()},
  {projectId: 4, columnId: 14, createdAt: new Date(), updatedAt: new Date()},
  {projectId: 4, columnId: 15, createdAt: new Date(), updatedAt: new Date()},
  {projectId: 4, columnId: 16, createdAt: new Date(), updatedAt: new Date()},
]
