const timeStamp = new Date()

const getCompletionDate = () => {
  const newDate = timeStamp.setDate(
    timeStamp.getDate() + Math.ceil(Math.random() * 5)
  )

  return newDate
}

module.exports = [
  {
    name: 'refactor components',
    isActiveBadge: false,
    completionDate: getCompletionDate(),
    editTimeStamp: timeStamp,
    createdBy: 'Daniel Shapiro',
    index: 0,
  },
  {
    name: 'marketing work',
    isActiveBadge: true,
    completionDate: getCompletionDate(),
    editTimeStamp: timeStamp,
    createdBy: 'David Ahn',
    index: 1,
  },
  {
    name: 'design logo',
    isActiveBadge: false,
    completionDate: getCompletionDate(),
    editTimeStamp: timeStamp,
    createdBy: 'Gene Kaufman',
    index: 0,
  },
  {
    name: 'design header',
    isActiveBadge: true,
    completionDate: getCompletionDate(),
    editTimeStamp: timeStamp,
    createdBy: 'Johnny Vazquez',
    index: 1,
  },
  {
    name: 'update vscode',
    isActiveBadge: false,
    completionDate: getCompletionDate(),
    editTimeStamp: timeStamp,
    createdBy: 'Daniel Shapiro',
    index: 0,
  },
  {
    name: 'update oauth',
    isActiveBadge: true,
    completionDate: getCompletionDate(),
    editTimeStamp: timeStamp,
    createdBy: 'David Ahn',
    index: 1,
  },
  {
    name: 'changeover localSecrets.js',
    isActiveBadge: false,
    completionDate: getCompletionDate(),
    editTimeStamp: timeStamp,
    createdBy: 'Gene Kaufman',
    index: 0,
  },
  {
    name: 'oversee merge',
    isActiveBadge: true,
    completionDate: getCompletionDate(),
    editTimeStamp: timeStamp,
    createdBy: 'Johnny Vazquez',
    index: 1,
  },
  {
    name: 'build component tree',
    isActiveBadge: false,
    completionDate: getCompletionDate(),
    editTimeStamp: timeStamp,
    createdBy: 'Daniel Shapiro',
    index: 0,
  },
  {
    name: 'diagram changes',
    isActiveBadge: true,
    completionDate: getCompletionDate(),
    editTimeStamp: timeStamp,
    createdBy: 'David Ahn',
    index: 1,
  },
  {
    name: 'update layout',
    isActiveBadge: false,
    completionDate: getCompletionDate(),
    editTimeStamp: timeStamp,
    createdBy: 'Gene Kaufman',
    index: 0,
  },
  {
    name: 'modularize css',
    isActiveBadge: true,
    completionDate: getCompletionDate(),
    editTimeStamp: timeStamp,
    createdBy: 'Johnny Vazquez',
    index: 1,
  },
  {
    name: 'write user stories',
    isActiveBadge: false,
    completionDate: getCompletionDate(),
    editTimeStamp: timeStamp,
    createdBy: 'Daniel Shapiro',
    index: 0,
  },
  {
    name: 'refactor db',
    isActiveBadge: true,
    completionDate: getCompletionDate(),
    editTimeStamp: timeStamp,
    createdBy: 'David Ahn',
    index: 1,
  },
  {
    name: 'update models',
    isActiveBadge: false,
    completionDate: getCompletionDate(),
    editTimeStamp: timeStamp,
    createdBy: 'Gene Kaufman',
    index: 0,
  },
  {
    name: 'write gatekeeping middleware',
    isActiveBadge: true,
    completionDate: getCompletionDate(),
    editTimeStamp: timeStamp,
    createdBy: 'Johnny Vazquez',
    index: 1,
  },
  {
    name: 'reverse linked list',
    isActiveBadge: false,
    completionDate: getCompletionDate(),
    editTimeStamp: timeStamp,
    createdBy: 'Daniel Shapiro',
    index: 0,
  },
  {
    name: 'buy popcorn',
    isActiveBadge: true,
    completionDate: getCompletionDate(),
    editTimeStamp: timeStamp,
    createdBy: 'David Ahn',
    index: 1,
  },
  {
    name: 'play guitar hero',
    isActiveBadge: false,
    completionDate: getCompletionDate(),
    editTimeStamp: timeStamp,
    createdBy: 'Gene Kaufman',
    index: 0,
  },
  {
    name: 'deploy on heroku',
    isActiveBadge: true,
    completionDate: getCompletionDate(),
    editTimeStamp: timeStamp,
    createdBy: 'Johnny Vazquez',
    index: 1,
  },
  {
    name: 'rewrite markup',
    isActiveBadge: false,
    completionDate: getCompletionDate(),
    editTimeStamp: timeStamp,
    createdBy: 'Daniel Shapiro',
    index: 0,
  },
  {
    name: 'purchase snacks',
    isActiveBadge: true,
    completionDate: getCompletionDate(),
    editTimeStamp: timeStamp,
    createdBy: 'David Ahn',
    index: 1,
  },
  {
    name: 'reboot server',
    isActiveBadge: false,
    completionDate: getCompletionDate(),
    editTimeStamp: timeStamp,
    createdBy: 'Gene Kaufman',
    index: 0,
  },
  {
    name: 'install centOS',
    isActiveBadge: true,
    completionDate: getCompletionDate(),
    editTimeStamp: timeStamp,
    createdBy: 'Johnny Vazquez',
    index: 1,
  },
  {
    name: 'play backgammon',
    isActiveBadge: false,
    completionDate: getCompletionDate(),
    editTimeStamp: timeStamp,
    createdBy: 'Daniel Shapiro',
    index: 0,
  },
  {
    name: 'eat more greens',
    isActiveBadge: true,
    completionDate: getCompletionDate(),
    editTimeStamp: timeStamp,
    createdBy: 'David Ahn',
    index: 1,
  },
  {
    name: 'update schema',
    isActiveBadge: false,
    completionDate: getCompletionDate(),
    editTimeStamp: timeStamp,
    createdBy: 'Gene Kaufman',
    index: 0,
  },
  {
    name: 'learn sass',
    isActiveBadge: true,
    completionDate: getCompletionDate(),
    editTimeStamp: timeStamp,
    createdBy: 'Johnny Vazquez',
    index: 1,
  },
  {
    name: 'convert to context',
    isActiveBadge: false,
    completionDate: getCompletionDate(),
    editTimeStamp: timeStamp,
    createdBy: 'Daniel Shapiro',
    index: 0,
  },
  {
    name: 'refactor store',
    isActiveBadge: true,
    completionDate: getCompletionDate(),
    editTimeStamp: timeStamp,
    createdBy: 'David Ahn',
    index: 1,
  },
  {
    name: 'play guitar hero again',
    isActiveBadge: false,
    completionDate: getCompletionDate(),
    editTimeStamp: timeStamp,
    createdBy: 'Gene Kaufman',
    index: 0,
  },
  {
    name: 'deploy on Travis-CI',
    isActiveBadge: true,
    completionDate: getCompletionDate(),
    editTimeStamp: timeStamp,
    createdBy: 'Johnny Vazquez',
    index: 1,
  },
]
