module.exports = [
  {
    name: 'refactor components',
    description: '### markdown is cool!',
    isActiveBadge: false,
    completionDate: '4/1/2021',
    createdBy: 'Albert Turtlesworth',
  },
  {
    name: 'marketing work',
    description: '### markdown is cool!',
    isActiveBadge: true,
    completionDate: '4/2/2021',
    createdBy: 'Albert Turtlesworth',
  },
  {
    name: 'design logo',
    description: '### markdown is cool!',
    isActiveBadge: false,
    completionDate: '4/3/2021',
    createdBy: 'Albert Turtlesworth',
  },
  {
    name: 'design header',
    description: '### markdown is cool!',
    isActiveBadge: true,
    completionDate: '4/4/2021',
    createdBy: 'Albert Turtlesworth',
  },
  {
    name: 'update vscode',
    description: '### markdown is cool!',
    isActiveBadge: false,
    completionDate: '4/5/2021',
    createdBy: 'Albert Turtlesworth',
  },
  {
    name: 'update oauth',
    description: '### markdown is cool!',
    isActiveBadge: true,
    completionDate: '4/6/2021',
    createdBy: 'Albert Turtlesworth',
  },
  {
    name: 'changeover localSecrets.js',
    description: '### markdown is cool!',
    isActiveBadge: false,
    completionDate: '4/7/2021',
    createdBy: 'Albert Turtlesworth',
  },
  {
    name: 'oversee merge',
    description: '### markdown is cool!',
    isActiveBadge: true,
    completionDate: '4/8/2021',
    createdBy: 'Albert Turtlesworth',
  },
  {
    name: 'build component tree',
    description: '### markdown is cool!',
    isActiveBadge: false,
    completionDate: '4/9/2021',
    createdBy: 'Albert Turtlesworth',
  },
  {
    name: 'diagram changes',
    description: '### markdown is cool!',
    isActiveBadge: true,
    completionDate: '4/10/2021',
    createdBy: 'Albert Turtlesworth',
  },
  {
    name: 'update layout',
    description: '### markdown is cool!',
    isActiveBadge: false,
    completionDate: '4/11/2021',
    createdBy: 'Albert Turtlesworth',
  },
  {
    name: 'modularize css',
    description: '### markdown is cool!',
    isActiveBadge: true,
    completionDate: '4/12/2021',
    createdBy: 'Albert Turtlesworth',
  },
  {
    name: 'write user stories',
    description: '### markdown is cool!',
    isActiveBadge: false,
    completionDate: '4/13/2021',
    createdBy: 'Albert Turtlesworth',
  },
  {
    name: 'refactor db',
    description: '### markdown is cool!',
    isActiveBadge: true,
    completionDate: '4/14/2021',
    createdBy: 'Albert Turtlesworth',
  },
  {
    name: 'update models',
    description: '### markdown is cool!',
    isActiveBadge: false,
    completionDate: '4/15/2021',
    createdBy: 'Albert Turtlesworth',
  },
  {
    name: 'write gatekeeping middleware',
    description: '### markdown is cool!',
    isActiveBadge: true,
    completionDate: '4/16/2021',
    createdBy: 'Albert Turtlesworth',
  },
  {
    name: 'reverse linked list',
    description: '### markdown is cool!',
    isActiveBadge: false,
    completionDate: '4/17/2021',
    createdBy: 'Albert Turtlesworth',
  },
  {
    name: 'buy popcorn',
    description: '### markdown is cool!',
    isActiveBadge: true,
    completionDate: '4/18/2021',
    createdBy: 'Albert Turtlesworth',
  },
  {
    name: 'play guitar hero',
    description: '### markdown is cool!',
    isActiveBadge: false,
    completionDate: '4/19/2021',
    createdBy: 'Albert Turtlesworth',
  },
  {
    name: 'deploy on heroku',
    description: '### markdown is cool!',
    isActiveBadge: true,
    completionDate: '4/20/2021',
    createdBy: 'Albert Turtlesworth',
  },
  {
    name: 'rewrite markup',
    description: '### markdown is cool!',
    isActiveBadge: false,
    completionDate: '4/9/2021',
    createdBy: 'Albert Turtlesworth',
  },
  {
    name: 'purchase snacks',
    description: '### markdown is cool!',
    isActiveBadge: true,
    completionDate: '4/10/2021',
    createdBy: 'Albert Turtlesworth',
  },
  {
    name: 'reboot server',
    description: '### markdown is cool!',
    isActiveBadge: false,
    completionDate: '4/11/2021',
    createdBy: 'Albert Turtlesworth',
  },
  {
    name: 'install centOS',
    description: '### markdown is cool!',
    isActiveBadge: true,
    completionDate: '4/12/2021',
    createdBy: 'Albert Turtlesworth',
  },
  {
    name: 'play backgammon',
    description: '### markdown is cool!',
    isActiveBadge: false,
    completionDate: '4/13/2021',
    createdBy: 'Albert Turtlesworth',
  },
  {
    name: 'eat more greens',
    description: '### markdown is cool!',
    isActiveBadge: true,
    completionDate: '4/14/2021',
    createdBy: 'Albert Turtlesworth',
  },
  {
    name: 'update schema',
    description: '### markdown is cool!',
    isActiveBadge: false,
    completionDate: '4/15/2021',
    createdBy: 'Albert Turtlesworth',
  },
  {
    name: 'learn sass',
    description: '### markdown is cool!',
    isActiveBadge: true,
    completionDate: '4/16/2021',
    createdBy: 'Albert Turtlesworth',
  },
  {
    name: 'convert to context',
    description: '### markdown is cool!',
    isActiveBadge: false,
    completionDate: '4/17/2021',
    createdBy: 'Albert Turtlesworth',
  },
  {
    name: 'refactor store',
    description: '### markdown is cool!',
    isActiveBadge: true,
    completionDate: '4/18/2021',
    createdBy: 'Albert Turtlesworth',
  },
  {
    name: 'play guitar hero again',
    description: '### markdown is cool!',
    isActiveBadge: false,
    completionDate: '4/19/2021',
    createdBy: 'Albert Turtlesworth',
  },
  {
    name: 'deploy on Travis-CI',
    description: '### markdown is cool!',
    isActiveBadge: true,
    completionDate: '4/20/2021',
    createdBy: 'Albert Turtlesworth',
  },
]
